name: freetype_dart
version: 1.0.0
description: freetype dart bindings
homepage: https://github.com/insinfo/libpq_dart
repository: https://github.com/insinfo/libpq_dart

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies: 
  path: ^1.9.0
  ffi: ^2.1.0
  ffigen: ^11.0.0

#dev_dependencies:


ffigen:
  name: 'LibpqBindings'
  llvm-path:  
    - 'C:\llvm'
  output: 'lib/src/generated_bindings.dart'
  headers:
    entry-points:            
      - 'libpq\include\libpq-fe.h'        
    include-directives:
      - 'libpq\include\**'

